spring.application.name=server
spring.datasource.url=jdbc:postgresql://localhost:5432/matchme
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Allow larger profile picture uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

socketio.host=0.0.0.0
socketio.port=8081

