spring.application.name=server
spring.datasource.url=jdbc:postgresql://localhost:5432/matchme
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Allow larger profile picture uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=myCG7THHUFuK7OTNeQ1qrxE8UShTPJF+CtIF4NLIBVFQoSOm4TzGRRBgnQmEQERZVxpYPtFrYXAI0C7vEH4FnQ==
jwt.expirationMs=86400000

logging.level.org.springframework.security=DEBUG


